### ISSUE TITLE
Switch on Union type

### ISSUE THREAD

**Issue by jgoux** [Gozala/typed-immutable#1]
Hello,
thanks for this useful library !
Is it possible to switch/if/match on an Union type to determine the underlying concrete type ?

**Comment by Gozala** [comment]
@jgoux if I understand you correctly what you're asking for is something along this lines isn't it ?

```js
Union(A, B).isTypeOf(x)
```

If so I did end up wrapping `Union` from this library for exactly that: 

https://github.com/mozilla/browser.html/blob/master/src/common/typed.js

With chat code I was able do something like this:

```js
const C = Union({X, Y})
C.isTypeOf(X()) // => true
```

I do want to add something along those lines into this library. There is also #4 for adding some helpers for doing type matching.

**Comment by Gozala** [comment]
Ok closing this in favor of #4

**Comment by Gozala** [comment]
Unfortunately I am no longer able to maintain this project, I apologize. If someone wishes to step up and take leadership of this project please respond to #21
